# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/buddy/configs/loader.ipynb.

# %% auto 0
__all__ = ['load_config', 'get_model_config', 'get_settings_config', 'get_tools_config', 'get_paths_config', 'get_mlflow_config',
           'get_reasoning_config']

# %% ../../nbs/buddy/configs/loader.ipynb 1
import toml
import os
from pathlib import Path


# %% ../../nbs/buddy/configs/loader.ipynb 2
def load_config():
    """Load configuration from config.toml"""
    config_path = Path(__file__).parent / "config.toml"
    
    if not config_path.exists():
        raise FileNotFoundError(f"Config file not found: {config_path}")
    
    with open(config_path, 'r') as f:
        config = toml.load(f)
    
    return config

def get_model_config():
    """Get model configuration"""
    config = load_config()
    return config.get('model', {})

def get_settings_config():
    """Get settings configuration"""
    config = load_config()
    return config.get('settings', {})

def get_tools_config():
    """Get tools configuration"""
    config = load_config()
    return config.get('tools', {})

def get_paths_config():
    """Get paths configuration"""
    config = load_config()
    return config.get('paths', {})

def get_mlflow_config():
    """Get MLflow configuration"""
    config = load_config()
    return config.get('mlflow', {})

def get_reasoning_config():
    """Get reasoning configuration"""
    config = load_config()
    return config.get('reasoning', {})

