# AUTOGENERATED! DO NOT EDIT! File to edit: ../../../nbs/buddy/backend/agents/planner/main.ipynb.

# %% auto 0
__all__ = ['main']

# %% ../../../nbs/buddy/backend/agents/planner/main.ipynb 1
import asyncio
from .executor import DynamicTaskExecutor

async def main():
    """Production demo with proper error handling"""
    try:
        # Use model from config.toml
        executor = DynamicTaskExecutor()
        
        user_request = "Build a web scraping framework with rate limiting and data storage"
        
        # Execute project
        result = await executor.execute_project(user_request)
        
    except KeyboardInterrupt:
        print("\n⚠️ Execution interrupted by user.")
    except Exception as e:
        print(f"❌ Execution failed: {e}")

