# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/buddy/backend/tools/base.ipynb.

# %% auto 0
__all__ = ['Tool']

# %% ../../nbs/buddy/backend/tools/base.ipynb 1
from abc import ABC, abstractmethod
from typing import Dict, Any, List

# %% ../../nbs/buddy/backend/tools/base.ipynb 2
class Tool(ABC):
    """Abstract base class for all tools."""
    
    @abstractmethod
    def get_tool_schema(self) -> Dict[str, Any]:
        """Return the OpenAI-compatible tool schema."""
        pass
    
    @abstractmethod
    def execute(self, **kwargs) -> Dict[str, Any]:
        """Execute the tool with the provided arguments."""
        pass

    @property
    def name(self) -> str:
        """Return the name of the tool."""
        return self.__class__.__name__.lower().replace("tool", "")
