# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/buddy/backend/tools/intelligence/debate_agent.ipynb.

# %% auto 0
__all__ = ['DebateTool']

# %% ../../nbs/buddy/backend/tools/intelligence/debate_agent.ipynb 1
from typing import Dict, Any
from .base import BaseTool, ToolMetadata, ToolCategory
import asyncio

class DebateTool(BaseTool):
    """Tool wrapper for DebateAgent"""
    
    def __init__(self):
        super().__init__(ToolMetadata(
            name="debate",
            description="Multi-perspective analysis for comparison questions and decision making",
            category=ToolCategory.INTELLIGENCE
        ))
    
    def execute(self, topic: str, context: str = "", max_rounds: int = 2) -> Dict[str, Any]:
        """Execute debate analysis using DebateAgent"""
        try:
            from ..agent.debater import create_debate
            
            # Run debate asynchronously
            loop = asyncio.new_event_loop()
            asyncio.set_event_loop(loop)
            
            try:
                result = loop.run_until_complete(
                    create_debate(
                        topic=topic,
                        context=context,
                        max_rounds=max_rounds
                    )
                )
                return {"success": True, "result": result}
            finally:
                loop.close()
                
        except Exception as e:
            return {"success": False, "error": str(e)}
    
    def get_parameters_schema(self) -> Dict[str, Any]:
        return {
            "type": "object",
            "properties": {
                "topic": {
                    "type": "string",
                    "description": "The topic or question to analyze"
                },
                "context": {
                    "type": "string", 
                    "description": "Additional context for the analysis",
                    "default": ""
                },
                "max_rounds": {
                    "type": "integer",
                    "description": "Maximum number of debate rounds",
                    "default": 2
                }
            },
            "required": ["topic"]
        }

