# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/buddy/backend/tools/display.ipynb.

# %% auto 0
__all__ = ['ToolExecutionDisplay']

# %% ../../nbs/buddy/backend/tools/display.ipynb 1
import json

class ToolExecutionDisplay:
    """Simple display for tool execution"""
    
    def show_tool_start(self, tool_name: str, trusted: bool = False, args: dict = None):
        """Show tool execution start with arguments"""
        trust_text = " (trusted)" if trusted else ""
        print(f"🛠️ Executing {tool_name}{trust_text}")
        if tool_name == "execute_bash":   
            if args:
                print(f"Command: {args.get('command')}")
                print(f"Summary : {args.get('summary')}")
    
    def show_tool_error(self, tool_name: str, error: str):
        """Show tool execution error"""
        print(f"❌ {tool_name}: {error}")
    
    def show_tool_result(self, tool_name: str, result: dict):
        """Show tool execution result"""
        print(f"✅ {tool_name} result:")
        print(f"   {json.dumps(result, indent=2)}")

